insert into mascot values ('Lucky the Leprechaun', 'Celtics', 'Human');
insert into mascot values ('Harry the _', 'Hawks', 'Animal');
insert into mascot values ('Hugo the _', 'Hornets', 'Animal');
insert into mascot values ('Benny the _', 'Bulls', 'Animal');
insert into mascot values ('Moondog', 'Cavaliers', 'Animal');
insert into mascot values ('Champ', 'Mavericks', 'Animal');
insert into mascot values ('Hooper', 'Pistons', 'Animal');
insert into mascot values ('Clutch the Bear', 'Rockets', 'Animal');
insert into mascot values ('Boomer', 'Pacers', 'Animal');
insert into mascot values ('Chuck the Condor', 'Clippers', 'Animal');
insert into mascot values ('Burnie', 'Heat', 'Basketball');
insert into mascot values ('Bango', 'Bucks', 'Animal');
insert into mascot values ('Crunch the _', 'Timberwolves', 'Animal');
insert into mascot values ('Pierre the _', 'Pelicans', 'Animal');
insert into mascot values ('Rumble the Bison', 'Thunder', 'Animal');
insert into mascot values ('Stuff the Magic Dragon', 'Magic', 'Mythical Creature');
insert into mascot values ('Franklin', '76ers', 'Animal');
insert into mascot values ('Go the Gorilla', 'Suns', 'Animal');
insert into mascot values ('Slamson the Lion', 'Kings', 'Animal');
insert into mascot values ('Coyote', 'Spurs', 'Animal');